layout_spectrum: 1
typography_spectrum: 0.9017185
color:
  saturation: 0.6294687
  lightness: 0.5622986
  brandStrength: 0.7076148
  brandColors:
    - '#1C1D1F'
    - '#48484A'
    - '#797778'
    - '#E4DAD9'
    - '#9E989A'
  rhythmicContrast: 0.9673181
name: MilSim City
