name: MilSim City
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9017185
title: 'Indoor Training Facility '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332931'
    - '#d7e3cd'
    - '#bebdb8'
    - '#9b8a82'
    - '#875a43'
  brandStrength: 0.7076148
  lightness: 0.5622986
  saturation: 0.6294687
  rhythmicContrast: 0.9673181
purpose: []
